image: prod-vm-docker-registry-01.clearpath.ai/build/jenkins_slave_focal
stages:
- test

before_script:
  - apt-get install python3-pip python3-wheel
  - python3 -m venv /tmp/venv
  - /tmp/venv/bin/pip install -U coverage nose setuptools wheel
  - /tmp/venv/bin/pip install -U .

nosetests:
  stage: test
  script:
  - /tmp/venv/bin/coverage run --source colcon_distro -m nose test
  - /tmp/venv/bin/coverage report
  - /tmp/venv/bin/coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
    expire_in: 1 week

deploy:
   only:
     - tags
   script:
     - python3 setup.py sdist bdist_wheel upload -r local
