image: prod-vm-docker-registry-01.clearpath.ai/build/jenkins_slave_focal

before_script:
  - apt-get install python3-pip python3-wheel
  - pip3 install -U coverage nose setuptools wheel
  - pip3 install -U .

test:
  script:
  - coverage run --source colcon_distro -m nose test
  - coverage report
  - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
    expire_in: 1 week

deploy:
   only:
     - tags
   script:
     - python3 setup.py sdist bdist_wheel upload -r local

pages:
  stage: deploy
  script:
  - pip3 install -U sphinx
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - master
